#line 2 "asm_scan.c"

#line 4 "asm_scan.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer asm__create_buffer
#define yy_delete_buffer asm__delete_buffer
#define yy_flex_debug asm__flex_debug
#define yy_init_buffer asm__init_buffer
#define yy_flush_buffer asm__flush_buffer
#define yy_load_buffer_state asm__load_buffer_state
#define yy_switch_to_buffer asm__switch_to_buffer
#define yyin asm_in
#define yyleng asm_leng
#define yylex asm_lex
#define yylineno asm_lineno
#define yyout asm_out
#define yyrestart asm_restart
#define yytext asm_text
#define yywrap asm_wrap
#define yyalloc asm_alloc
#define yyrealloc asm_realloc
#define yyfree asm_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE asm_restart(asm_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int asm_leng;

extern FILE *asm_in, *asm_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE asm_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-asm_lineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
 */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < asm_leng; ++yyl )\
                    if ( asm_text[yyl] == '\n' )\
                        --asm_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up asm_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up asm_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via asm_restart()), so that the user can continue scanning by
	 * just pointing asm_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when asm_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int asm_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow asm_wrap()'s to do buffer switches
 * instead of setting up a fresh asm_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void asm_restart (FILE *input_file  );
void asm__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE asm__create_buffer (FILE *file,int size  );
void asm__delete_buffer (YY_BUFFER_STATE b  );
void asm__flush_buffer (YY_BUFFER_STATE b  );
void asm_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void asm_pop_buffer_state (void );

static void asm_ensure_buffer_stack (void );
static void asm__load_buffer_state (void );
static void asm__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER asm__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE asm__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE asm__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE asm__scan_bytes (yyconst char *bytes,int len  );

void *asm_alloc (yy_size_t  );
void *asm_realloc (void *,yy_size_t  );
void asm_free (void *  );

#define yy_new_buffer asm__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        asm_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            asm__create_buffer(asm_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        asm_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            asm__create_buffer(asm_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define asm_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *asm_in = (FILE *) 0, *asm_out = (FILE *) 0;

typedef int yy_state_type;

extern int asm_lineno;

int asm_lineno = 1;

extern char *asm_text;
#define yytext_ptr asm_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up asm_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	asm_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 41
#define YY_END_OF_BUFFER 42
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[216] =
    {   0,
        0,    0,    3,    3,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   42,   40,    1,   39,   16,   21,
       40,   40,   40,   26,   12,   37,   37,   37,   37,   40,
       37,   37,   37,   37,    1,   28,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,    3,    4,
        5,    9,   11,   41,   13,   15,   41,   17,   19,   20,
       41,   22,   24,   25,   41,   36,   40,   35,    1,    0,
       26,   26,    0,    0,    2,    8,    0,   26,   37,   37,
       37,   37,   38,   37,   37,   37,   37,    1,   28,    0,
       27,   34,   34,   34,   34,   34,   34,   34,   34,   34,

       34,   34,   34,   34,    3,    4,    5,    6,    5,    7,
        9,    0,   10,   13,    0,   14,   17,    0,   18,   22,
        0,   23,   35,    0,    0,    0,   26,   37,   33,   37,
       37,   31,   29,   37,   27,   34,   34,   34,   34,   34,
       33,   34,   34,   34,   34,   34,   31,   29,   34,    0,
       26,   31,    0,    0,   37,   37,   37,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,    0,    0,   26,
       37,   37,   30,   34,   34,   34,   34,   32,   34,   34,
       34,   34,   30,   30,   37,   37,   34,   34,   34,   34,
       34,   34,   34,   37,   34,   34,   34,   34,   34,   37,

       34,   34,   34,   37,   34,   34,   34,   37,   34,   34,
       34,   34,   34,   34,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    7,    1,
        1,    8,    9,    1,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    1,    1,    1,
        1,    1,    1,   14,   15,   16,   17,   18,   19,   18,
       20,   18,   18,   21,   18,   22,   23,   24,   25,   18,
       18,   26,   27,   28,   18,   18,   18,   29,   30,   18,
        1,   31,    1,    1,   32,    1,   33,   18,   34,   18,

       35,   18,   18,   18,   18,   36,   18,   37,   38,   18,
       39,   18,   40,   41,   42,   18,   43,   18,   18,   18,
       18,   18,    1,    1,    1,    1,    1,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,

       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18
    } ;

static yyconst flex_int32_t yy_meta[44] =
    {   0,
        1,    2,    3,    1,    4,    1,    5,    6,    1,    1,
        1,    1,    7,    1,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8
    } ;

static yyconst flex_int16_t yy_base[233] =
    {   0,
        0,   43,   84,   85,   86,   87,   88,   91,   92,   93,
       96,   97,  128,  159,  427,  428,  103,  428,  428,  428,
       95,  108,  101,  103,  428,    0,  394,  396,  394,  420,
      389,  381,  378,  386,  143,  416,  395,    0,  384,   86,
      393,  387,  394,  382,  378,  370,  367,  375,  404,  428,
      145,  375,  428,  402,  373,  428,  400,  371,  428,  428,
      147,  370,  428,  428,  148,  428,  387,    0,  152,  386,
      163,  162,  358,  364,  428,  428,  383,  428,    0,  373,
      366,  370,  428,  355,  348,  349,  355,  176,  386,  385,
        0,    0,  358,  164,  357,  356,  358,  366,  357,  357,

      342,  335,  336,  342,  372,  428,  176,  428,  184,  428,
      343,    0,  428,  342,    0,  428,  341,  366,  428,  339,
      362,  428,    0,  185,  325,  333,  180,  351,    0,  349,
      327,    0,    0,  322,    0,  343,  337,  345,  329,  332,
        0,  341,  337,  327,  338,  316,    0,    0,  311,  338,
      337,  428,  308,  191,  332,  322,  307,  321,  316,  327,
      319,  311,  325,  315,  312,  312,  297,  296,  321,  320,
      313,  309,    0,  302,  303,  309,  311,    0,  297,  289,
      280,  287,    0,  428,  279,  261,  254,  241,  248,  244,
      236,  241,  182,  189,  182,  189,  191,  179,  184,  192,

      174,  181,  188,  179,  165,  149,  135,  125,  111,   94,
       93,   88,   72,   82,  428,  215,  223,  231,  239,  247,
      255,  257,  264,  266,  274,  282,  290,  298,  306,  314,
      316,  318
    } ;

static yyconst flex_int16_t yy_def[233] =
    {   0,
      215,  215,  216,  216,  217,  217,  218,  218,  219,  219,
      220,  220,  221,  221,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  222,  222,  222,  222,  215,
      222,  222,  222,  222,  215,  223,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  225,  215,
      226,  227,  215,  227,  228,  215,  228,  229,  215,  215,
      229,  230,  215,  215,  230,  215,  215,  231,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  222,  222,
      222,  222,  215,  222,  222,  222,  222,  215,  223,  223,
      232,  224,  224,  224,  224,  224,  224,  224,  224,  224,

      224,  224,  224,  224,  225,  215,  226,  215,  226,  215,
      227,  227,  215,  228,  228,  215,  229,  229,  215,  230,
      230,  215,  231,  215,  215,  215,  215,  222,  222,  222,
      222,  222,  222,  222,  232,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  215,
      215,  215,  215,  215,  222,  222,  222,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  215,  215,  215,
      222,  222,  222,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  215,  222,  222,  224,  224,  224,  224,
      224,  224,  224,  222,  224,  224,  224,  224,  224,  222,

      224,  224,  224,  222,  224,  224,  224,  222,  224,  224,
      224,  224,  224,  224,    0,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215
    } ;

static yyconst flex_int16_t yy_nxt[472] =
    {   0,
       16,   17,   18,   17,   19,   16,   20,   16,   16,   21,
       22,   23,   24,   25,   26,   26,   27,   26,   28,   26,
       26,   26,   26,   26,   26,   26,   29,   26,   26,   26,
       30,   26,   26,   31,   32,   33,   26,   34,   26,   26,
       26,   26,   26,   16,   35,   18,   17,   19,   36,   20,
       16,   16,   21,   22,   23,   24,   25,   37,   38,   39,
       38,   40,   41,   42,   38,   38,   43,   38,   38,   44,
       38,   38,   38,   30,   38,   38,   45,   46,   47,   38,
       48,   38,   38,   38,   38,   38,   50,   50,   53,   53,
       56,   51,   51,   56,   59,   59,   60,   60,   63,   63,

      178,  178,   64,   64,   69,   70,   69,   71,   75,   95,
      214,  141,   76,   77,   96,   71,   54,   54,   57,  213,
       72,   57,   61,   61,   78,  212,   65,   65,   16,   17,
       66,   17,   19,   16,   20,   16,   16,   21,   67,   23,
       24,   25,   73,  129,   88,   74,   69,  108,   89,  119,
      122,  117,  109,   69,  120,   69,  110,  211,   30,   16,
       17,   66,   17,   19,   16,   20,   16,   16,   21,   67,
       23,   24,   25,   77,   72,   71,  210,   88,  108,   69,
      124,   89,  137,  215,   78,  138,  108,  215,  209,   30,
      139,  109,  127,  150,  150,  110,  124,  151,  154,  169,

      169,  208,  207,  170,  206,  205,  204,  203,  178,  202,
      201,  178,  200,  199,  154,   49,   49,   49,   49,   49,
       49,   49,   49,   52,   52,   52,   52,   52,   52,   52,
       52,   55,   55,   55,   55,   55,   55,   55,   55,   58,
       58,   58,   58,   58,   58,   58,   58,   62,   62,   62,
       62,   62,   62,   62,   62,   68,   68,   68,   68,   68,
       68,   68,   68,   79,   79,   91,  198,  197,  196,  141,
      178,   91,   92,   92,  105,  105,  105,  105,  105,  195,
      105,  105,  107,  107,  107,  107,  107,  107,  107,  107,
      111,  111,  194,  111,  111,  111,  111,  111,  114,  114,

      129,  114,  114,  114,  114,  114,  117,  117,  193,  178,
      117,  117,  117,  117,  120,  120,  192,  120,  191,  120,
      120,  120,  123,  123,  135,  135,  190,  189,  188,  187,
      186,  185,  170,  170,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  168,  151,
      151,  167,  148,  166,  165,  164,  163,  162,  161,  160,
      159,  158,  157,  133,  156,  155,  153,  152,  120,  121,
      117,  118,  115,  112,  106,  149,  148,  147,  146,  145,
      144,  143,  142,  141,  140,  136,   90,   90,  134,  133,
      132,  131,  130,  129,  128,  127,  126,  125,   72,   72,

      121,  118,  116,  115,  113,  112,  106,  104,  103,  102,
      101,  100,   99,   98,   97,   94,   93,   90,   87,   86,
       85,   84,   83,   82,   81,   80,  215,   15,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215
    } ;

static yyconst flex_int16_t yy_chk[472] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    3,    4,    5,    6,
        7,    3,    4,    8,    9,   10,    9,   10,   11,   12,

      214,  213,   11,   12,   17,   21,   17,   21,   23,   40,
      212,  211,   23,   24,   40,   24,    5,    6,    7,  210,
       22,    8,    9,   10,   24,  209,   11,   12,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   22,  208,   35,   22,   35,   51,   35,   61,
       65,   61,   51,   69,   65,   69,   51,  207,   13,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   71,   72,   71,  206,   88,  107,   88,
       72,   88,   94,  107,   71,   94,  109,  107,  205,   14,
       94,  109,  127,  124,  124,  109,   72,  124,  127,  154,

      154,  204,  203,  154,  202,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  127,  216,  216,  216,  216,  216,
      216,  216,  216,  217,  217,  217,  217,  217,  217,  217,
      217,  218,  218,  218,  218,  218,  218,  218,  218,  219,
      219,  219,  219,  219,  219,  219,  219,  220,  220,  220,
      220,  220,  220,  220,  220,  221,  221,  221,  221,  221,
      221,  221,  221,  222,  222,  223,  192,  191,  190,  189,
      188,  223,  224,  224,  225,  225,  225,  225,  225,  187,
      225,  225,  226,  226,  226,  226,  226,  226,  226,  226,
      227,  227,  186,  227,  227,  227,  227,  227,  228,  228,

      185,  228,  228,  228,  228,  228,  229,  229,  182,  181,
      229,  229,  229,  229,  230,  230,  180,  230,  179,  230,
      230,  230,  231,  231,  232,  232,  177,  176,  175,  174,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  160,  159,  158,  157,  156,  155,  153,  151,
      150,  149,  146,  145,  144,  143,  142,  140,  139,  138,
      137,  136,  134,  131,  130,  128,  126,  125,  121,  120,
      118,  117,  114,  111,  105,  104,  103,  102,  101,  100,
       99,   98,   97,   96,   95,   93,   90,   89,   87,   86,
       85,   84,   82,   81,   80,   77,   74,   73,   70,   67,

       62,   58,   57,   55,   54,   52,   49,   48,   47,   46,
       45,   44,   43,   42,   41,   39,   37,   36,   34,   33,
       32,   31,   30,   29,   28,   27,   15,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[42] =
    {   0,
0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 
    0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 
    0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int asm__flex_debug;
int asm__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *asm_text;
#line 1 "asm_scan.l"
#line 2 "asm_scan.l"
/*
 * Copyright (c) 2002, 2004, 2010 Tama Communications Corporation
 *
 * This file is part of GNU GLOBAL.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#ifdef HAVE_STRING_H
#include <string.h>
#else
#include <strings.h>
#endif

#define YYLTYPE		int

#include "internal.h"
#include "asm_parse.h"
#include "asm_res.h"
#include "die.h"
#include "linetable.h"
#include "strbuf.h"

#define lex_symbol_generation_rule(x) asm_ ## x
#define LEXLEX lex_symbol_generation_rule(lex)
#define LEXTEXT lex_symbol_generation_rule(text)
#define LEXLENG lex_symbol_generation_rule(leng)
#define LEXLINENO lex_symbol_generation_rule(lineno)
#define LEXRESTART lex_symbol_generation_rule(restart)
#define LEXLVAL lex_symbol_generation_rule(lval)
#define LEXLLOC lex_symbol_generation_rule(lloc)

#define YY_DECL	int LEXLEX(const struct parser_param *param)

#define YY_INPUT(buf, result, max_size) do {				\
	if ((result = linetable_read(buf, max_size)) == -1)		\
		result = YY_NULL;					\
} while (0)

#define ADD_SYM(tag, lno) do {						\
	LEXLVAL = strbuf_getlen(asm_symtable);				\
	LEXLLOC = (lno);						\
	strbuf_puts0(asm_symtable, tag);				\
} while (0)

#undef PUT
#define PUT(type, tag, lno) do {					\
	const char *line_image = linetable_get(lno, NULL);		\
	char *nl = strchr(line_image, '\n');				\
	if (nl != NULL)							\
		*nl = '\0';						\
	param->put(type, tag, lno, param->file, line_image, param->arg);\
	if (nl != NULL)							\
		*nl = '\n';						\
} while (0)

static int last_directive;



#line 755 "asm_scan.c"

#define INITIAL 0
#define C_COMMENT 1
#define CPP_COMMENT 2
#define GAS_COMMENT 3
#define STRING 4
#define LITERAL 5
#define PREPROCESSOR_LINE 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int asm_lex_destroy (void );

int asm_get_debug (void );

void asm_set_debug (int debug_flag  );

YY_EXTRA_TYPE asm_get_extra (void );

void asm_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *asm_get_in (void );

void asm_set_in  (FILE * in_str  );

FILE *asm_get_out (void );

void asm_set_out  (FILE * out_str  );

int asm_get_leng (void );

char *asm_get_text (void );

int asm_get_lineno (void );

void asm_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int asm_wrap (void );
#else
extern int asm_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;

    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( asm_text, asm_leng, 1, asm_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( asm_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( asm_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, asm_in))==0 && ferror(asm_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(asm_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int asm_lex (void);

#define YY_DECL int asm_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after asm_text and asm_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( asm_leng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(asm_text[asm_leng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 91 "asm_scan.l"


 /* Ignore spaces */
#line 963 "asm_scan.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! asm_in )
			asm_in = stdin;

		if ( ! asm_out )
			asm_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			asm_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				asm__create_buffer(asm_in,YY_BUF_SIZE );
		}

		asm__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of asm_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 216 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 215 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < asm_leng; ++yyl )
				if ( asm_text[yyl] == '\n' )
					   
    asm_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 94 "asm_scan.l"

	YY_BREAK
/* C style comment */
case 2:
YY_RULE_SETUP
#line 97 "asm_scan.l"
{ yy_push_state(C_COMMENT); }
	YY_BREAK

case 3:
YY_RULE_SETUP
#line 99 "asm_scan.l"

	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 100 "asm_scan.l"

	YY_BREAK
case 5:
YY_RULE_SETUP
#line 101 "asm_scan.l"

	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 102 "asm_scan.l"

	YY_BREAK
case 7:
YY_RULE_SETUP
#line 103 "asm_scan.l"
{ yy_pop_state(); }
	YY_BREAK
case YY_STATE_EOF(C_COMMENT):
#line 104 "asm_scan.l"
{
		if (param->flags & PARSER_WARNING)
			warning("unexpected eof. [+%d %s]", LEXLINENO, param->file);
		yyterminate();
	}
	YY_BREAK

/* C++ style line comment */
case 8:
YY_RULE_SETUP
#line 112 "asm_scan.l"
{ yy_push_state(CPP_COMMENT); }
	YY_BREAK

case 9:
YY_RULE_SETUP
#line 114 "asm_scan.l"

	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 115 "asm_scan.l"

	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 116 "asm_scan.l"
{ yy_pop_state(); unput('\n'); }
	YY_BREAK

/* gas style line comment */
case 12:
YY_RULE_SETUP
#line 120 "asm_scan.l"
{ yy_push_state(GAS_COMMENT); }
	YY_BREAK

case 13:
YY_RULE_SETUP
#line 122 "asm_scan.l"

	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 123 "asm_scan.l"

	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 124 "asm_scan.l"
{ yy_pop_state(); unput('\n'); }
	YY_BREAK

/* String */
case 16:
YY_RULE_SETUP
#line 128 "asm_scan.l"
{ yy_push_state(STRING); }
	YY_BREAK

case 17:
YY_RULE_SETUP
#line 130 "asm_scan.l"

	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 131 "asm_scan.l"

	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 132 "asm_scan.l"
{ yy_pop_state(); unput('\n'); return ASM_CONST; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 133 "asm_scan.l"
{ yy_pop_state(); return ASM_CONST; }
	YY_BREAK

/* Character */
case 21:
YY_RULE_SETUP
#line 137 "asm_scan.l"
{ yy_push_state(LITERAL); }
	YY_BREAK

case 22:
YY_RULE_SETUP
#line 139 "asm_scan.l"

	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 140 "asm_scan.l"

	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 141 "asm_scan.l"
{ yy_pop_state(); unput('\n'); return ASM_CONST; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 142 "asm_scan.l"
{ yy_pop_state(); return ASM_CONST; }
	YY_BREAK

/* Number */
case 26:
YY_RULE_SETUP
#line 146 "asm_scan.l"
{ return ASM_CONST; }
	YY_BREAK

case 27:
YY_RULE_SETUP
#line 149 "asm_scan.l"
{
		last_directive = asm_reserved_sharp(LEXTEXT, LEXLENG);
		switch (last_directive) {
		case 0:
			yy_push_state(CPP_COMMENT);
			break;
		case SHARP_DEFINE:
			yy_push_state(PREPROCESSOR_LINE);
			return ASM_DEFINE;
		case SHARP_UNDEF:
			yy_push_state(PREPROCESSOR_LINE);
			return ASM_UNDEF;
		default:
			yy_push_state(PREPROCESSOR_LINE);
			return ASM_DIRECTIVE;
		}
	}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 166 "asm_scan.l"
{
		last_directive = 0;
		yy_push_state(PREPROCESSOR_LINE);
		return ASM_DIRECTIVE;
	}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 171 "asm_scan.l"
{ return ASM_CALL; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 172 "asm_scan.l"
{ return ASM_MACRO; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 173 "asm_scan.l"
{ return ASM_EQU; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 174 "asm_scan.l"
{
		ADD_SYM(LEXTEXT, LEXLINENO); 
		return ASM_ENTRY;
	}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 178 "asm_scan.l"
{
		ADD_SYM(LEXTEXT, LEXLINENO);
		return ASM_EXT;
	}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 182 "asm_scan.l"
{ ADD_SYM(LEXTEXT, LEXLINENO); return ASM_LABEL; }
	YY_BREAK


case 35:
YY_RULE_SETUP
#line 186 "asm_scan.l"
{
		switch (last_directive) {
		case SHARP_IF:
		case SHARP_ELIF:
			if (strcmp(LEXTEXT, "defined") == 0)
				break;
			/* FALLTHROUGH */
		case SHARP_IFDEF:
		case SHARP_IFNDEF:
			PUT(PARSER_REF_SYM, LEXTEXT, LEXLINENO);
			break;
		default:
			ADD_SYM(LEXTEXT, LEXLINENO);
			return ASM_SYMBOL;
		}
	}
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 202 "asm_scan.l"
{ yy_pop_state(); return '\n'; }
	YY_BREAK

case 37:
YY_RULE_SETUP
#line 205 "asm_scan.l"
{ ADD_SYM(LEXTEXT, LEXLINENO); return ASM_SYMBOL; }
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 207 "asm_scan.l"

	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 208 "asm_scan.l"
{ return '\n'; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 209 "asm_scan.l"
{ return LEXTEXT[0]; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 211 "asm_scan.l"
ECHO;
	YY_BREAK
#line 1340 "asm_scan.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CPP_COMMENT):
case YY_STATE_EOF(GAS_COMMENT):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(LITERAL):
case YY_STATE_EOF(PREPROCESSOR_LINE):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed asm_in at a new source and called
			 * asm_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = asm_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( asm_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * asm_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of asm_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
		int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					asm_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			asm_restart(asm_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) asm_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 216 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 216 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 215);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;

    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up asm_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --asm_lineno;
	}

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;

	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					asm_restart(asm_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( asm_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve asm_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )

    asm_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void asm_restart  (FILE * input_file )
{

	if ( ! YY_CURRENT_BUFFER ){
        asm_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            asm__create_buffer(asm_in,YY_BUF_SIZE );
	}

	asm__init_buffer(YY_CURRENT_BUFFER,input_file );
	asm__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void asm__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		asm_pop_buffer_state();
	 *		asm_push_buffer_state(new_buffer);
     */
	asm_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	asm__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (asm_wrap()) processing, but the only time this flag
	 * is looked at is after asm_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void asm__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	asm_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE asm__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) asm_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in asm__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) asm_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in asm__create_buffer()" );

	b->yy_is_our_buffer = 1;

	asm__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with asm__create_buffer()
 * 
 */
    void asm__delete_buffer (YY_BUFFER_STATE  b )
{

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		asm_free((void *) b->yy_ch_buf  );

	asm_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a asm_restart() or at EOF.
 */
    static void asm__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;

	asm__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then asm__init_buffer was _probably_
     * called from asm_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
	}

        b->yy_is_interactive = 0;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void asm__flush_buffer (YY_BUFFER_STATE  b )
{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		asm__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void asm_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	asm_ensure_buffer_stack();

	/* This block is copied from asm__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
	{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from asm__switch_to_buffer. */
	asm__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void asm_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	asm__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		asm__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void asm_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)asm_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in asm_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)asm_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in asm_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE asm__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) asm_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in asm__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	asm__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to asm_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       asm__scan_bytes() instead.
 */
YY_BUFFER_STATE asm__scan_string (yyconst char * yystr )
{

	return asm__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to asm_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE asm__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) asm_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in asm__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = asm__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in asm__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) asm_alloc(new_size  );

		else
			(yy_start_stack) = (int *) asm_realloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up asm_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		asm_text[asm_leng] = (yy_hold_char); \
		(yy_c_buf_p) = asm_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		asm_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int asm_get_lineno  (void)
{

    return asm_lineno;
}

/** Get the input stream.
 * 
 */
FILE *asm_get_in  (void)
{
        return asm_in;
}

/** Get the output stream.
 * 
 */
FILE *asm_get_out  (void)
{
        return asm_out;
}

/** Get the length of the current token.
 * 
 */
int asm_get_leng  (void)
{
        return asm_leng;
}

/** Get the current token.
 * 
 */

char *asm_get_text  (void)
{
        return asm_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void asm_set_lineno (int  line_number )
{
    
    asm_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see asm__switch_to_buffer
 */
void asm_set_in (FILE *  in_str )
{
        asm_in = in_str ;
}

void asm_set_out (FILE *  out_str )
{
        asm_out = out_str ;
}

int asm_get_debug  (void)
{
        return asm__flex_debug;
}

void asm_set_debug (int  bdebug )
{
        asm__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from asm_lex_destroy(), so don't allocate here.
     */

    /* We do not touch asm_lineno unless the option is enabled. */
    asm_lineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    asm_in = stdin;
    asm_out = stdout;
#else
    asm_in = (FILE *) 0;
    asm_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * asm_lex_init()
     */
    return 0;
}

/* asm_lex_destroy is for both reentrant and non-reentrant scanners. */
int asm_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		asm__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		asm_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	asm_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        asm_free((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * asm_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *asm_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *asm_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void asm_free (void * ptr )
{
	free( (char *) ptr );	/* see asm_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 211 "asm_scan.l"



void
asm_initscan(void)
{
	LEXRESTART(NULL);
	LEXLINENO = 1;
}

